### ISSUE TITLE
[1.0.1-beta]TransformError:Unknown plugin "transform-flow-strip-types"

### ISSUE THREAD

**Issue by dyguests** [tomauty/react-native-chart#99] opened 2016-07-05 08:38 UTC
envirment:
    "react": "15.2.0",
    "react-native": "0.28.0",
    "react-native-chart": "^1.0.1-beta"

It's happen in a init project(do nothing except init),

And I add react-native-chart as same as you "Getting Started" Guide.

When I add `import Chart from 'react-native-chart';` in `index.ios.js`.
The project is crashed.

The log:
`TransformError:/.../Chart.js:Unknown plugin "transform-flow-strip-types" specified in "/.../$MY_PROJECT_NAME/node_modules/react-native-chart/.babelrc" at 0,attempted to resolve relative to "/.../$My_Project_NAME$/node_modules/react-native-chart"`

**Comment by dyguests** [comment] 2016-07-05 08:42
And It's not work on android.

**Comment by tomauty** [comment] 2016-07-07 13:21
Let's fix the first post first :) I'll update shortly.

**Comment by tomauty** [comment] 2016-07-07 13:23
I think the issue is that I'm including a bunch of stuff in the `npm publish` output that technically shouldn't be there (e.g. src, babelrc, etc). However for the sake of easier debugging I like to keep it in there during the beta phase. I'll add it to explicit dependencies so this doesn't happen, and make a note to remove it when we leave beta.

**Comment by tomauty** [comment] 2016-07-07 13:30
https://github.com/tomauty/react-native-chart/commit/7d362a85f4377fae2c87f277fc17acc0eb62a041

**Comment by tomauty** [comment] 2016-07-07 14:08
Fixed in `1.0.4-beta`

**Closed as completed by tomauty** 2016-07-07 14:08 UTC

**Comment by dyguests** [comment] 2016-07-08 01:29
O  O~,thanks.

and I'm expecting the release version(include android)....and Horizontal line chart.

:)

**Comment by dyguests** [comment] 2016-07-08 01:57
...Unhh...

envirment:
    "react": "15.2.0",
    "react-native": "0.29.0",
    "react-native-chart": "^1.0.4-beta"

I'd tried ,but,there is no line in Line Chart.

<img width="180" alt="2016-07-08 09 48 32" src="https://cloud.githubusercontent.com/assets/7933189/16675294/5271d484-44f2-11e6-8ab8-785373041343.png">

both happen in ios and android.

:(

**Comment by dyguests** [comment] 2016-07-08 01:59
here is the source:

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, {Component} from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View
} from 'react-native';
import Chart from 'react-native-chart';

const data = [
    [0, 1],
    [1, 3],
    [3, 7],
    [4, 9],
];

class Chart1 extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Chart
                    style={styles.chart}
                    data={data}
                    verticalGridStep={5}
                    type="line"/>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
    },
    chart: {
        width: 200,
        height: 200,
    },
});

AppRegistry.registerComponent('Chart1', () => Chart1);

```

**Comment by dyguests** [comment] 2016-07-08 02:10
The problem happen on type="line",other's type is ok.
(and type="pie" has missing some data at UI in android.).

:(

**Comment by tomauty** [comment] 2016-07-08 02:31
Line chart should be fixed tomorrow AM. Still debugging pie charts :/
